# Generated by Django 5.2.5 on 2025-08-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('vectorstore_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('COMPLETED', '完了'), ('FAILED', '失敗')], default='COMPLETED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
